Style
Farida-Hamid/Bookstore pull request #6
Opened 2022-09-23 14:39 UTC by Farida-Hamid

This is the last project for the Bookstore website. Now that all the functionality is done, I added styling. I used Zeplin as a collaboration tool.

2022-09-23 14:49 UTC, GzimAsani requested changes
### Hello @Farida-Hamid             :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your styling  :+1:  
 
 ## Required Changes 

- [x] Check the comment below :arrow_double_down: 






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 14:49 UTC, GzimAsani commented on src/components/Header.js
>        <Link to="/">BOOKS</Link>
- [ ] The categories color is different from the design, kindly update it 
YOurs: ![image](https://user-images.githubusercontent.com/62705947/191987747-81528b96-3d83-4a03-9450-95eacb0bc13a.png)
Design: ![image](https://user-images.githubusercontent.com/62705947/191987996-1ab1640b-fbfd-4f75-8596-12a2b31a6c16.png)

2022-09-23 14:49 UTC, GzimAsani commented on src/components/Book.js
> +      <button className="delete" type="button" onClick={deleteBook} value={id}>Delete</button>
- [ ] The design looks a lot different from yours, kindly updated it according to your design

YOurs: ![image](https://user-images.githubusercontent.com/62705947/191988406-e9cb0774-bf84-4e67-99ee-62e360383a4b.png)

Design:![image](https://user-images.githubusercontent.com/62705947/191988481-92cad623-5213-4b0f-9179-289efad76109.png)

2022-09-24 22:15 UTC, fobadara requested changes
# REQUIRES CHANGES ♻️ 
Hi @Farida-Hamid, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
✅ Linters are passing
✅ Good job following the best practices for commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
[OPTIONAL] I think you should tell us how we can get your code to our local machine and use it in your README
[OPTIONAL] The link to your MIT license in your README returns a 404 error

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 22:15 UTC, fobadara commented on src/components/Book.js
>    );
[REQUIRED] I that the previous reviewer didn't go into details. But what he means by looks a lot different includes the blue colour of the author's name, the percentage circle and every other thing in the Zeplin design irrespective of whether you created the functionality for them or not

| Zeplin Template|
|---------------|
|![image](https://user-images.githubusercontent.com/62938735/192120355-b2008510-f4f5-4cb0-b91d-9bb7ec92b505.png)|

2022-09-24 22:15 UTC, fobadara commented on src/components/Header.js
> -      <Link to="/categories">CATEGORIES</Link>
[REQUIRED] Kindly make the categories text even lighter

2022-09-30 12:55 UTC, uwadonat approved these changes
## Hi @Farida-Hamid,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Professional readme file ✔️

![image](https://user-images.githubusercontent.com/65860678/193274291-712d4e62-2a3d-4b9f-9c37-e9812a88a096.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-30 13:00 UTC, merged